// Datos de las personas del Centro de Ayuda
// Se usa tanto en help.html (para el listado) como en help-detalle.html (para el detalle en grande)
const personasAyuda = [
    {
        id: 1,
        nombre: "Mateo Sebastián",
        edad: 20,
        tipoCancer: "Linfoma",
        ubicacion: "San Salvador, San Salvador",
        meta: "Graduarse profesionalmente de la carrera de música y especializarse en composición.",
        telefono: "+503 7123-4567",
        foto: "persona1.jpe",
        recaudado: 805,
        objetivo: 1200,
        porcentaje: 67
    },
    {
        id: 2,
        nombre: "Camila Valentina",
        edad: 22,
        tipoCancer: "Cáncer de Tiroides",
        ubicacion: "Santa Tecla, La Libertad",
        meta: "Estudiar medicina forense en el extranjero para colaborar en el análisis de casos complejos.",
        telefono: "+503 7234-5678",
        foto: "persona3.jpg",
        recaudado: 2005,
        objetivo: 2500,
        porcentaje: 80
    },
    {
        id: 3,
        nombre: "Valeria Sofía",
        edad: 19,
        tipoCancer: "Leucemia",
        ubicacion: "Santa Ana, Santa Ana",
        meta: "Lograr estudiar la carrera de derecho para defender activamente los derechos civiles.",
        telefono: "+503 7345-6789",
        foto: "persona4.avif",
        recaudado: 1405,
        objetivo: 2000,
        porcentaje: 70
    },
    {
        id: 4,
        nombre: "Daniel Alejandro",
        edad: 24,
        tipoCancer: "Leucemia",
        ubicacion: "San Miguel, San Miguel",
        meta: "Costear el traslado y estadía de retorno para recibir tratamiento médico especializado cerca de su familia.",
        telefono: "+503 7456-7890",
        foto: "persona 2.avif",
        recaudado: 2005,
        objetivo: 3000,
        porcentaje: 67
    },
    {
        id: 5,
        nombre: "Gabriela Marie",
        edad: 21,
        tipoCancer: "Cáncer de Mama",
        ubicacion: "Antiguo Cuscatlán, La Libertad",
        meta: "Concluir su carrera de Licenciatura en Idiomas Modernos y ejercer como docente bilingüe.",
        telefono: "+503 7567-8901",
        foto: "persona5.jpg",
        recaudado: 950,
        objetivo: 1500,
        porcentaje: 63
    },
    {
        id: 6,
        nombre: "Diego Fernando",
        edad: 18,
        tipoCancer: "Cáncer de Colon",
        ubicacion: "Soyapango, San Salvador",
        meta: "Convertirse en Ingeniero en Sistemas y crear aplicaciones accesibles para la salud oncológica.",
        telefono: "+503 7678-9012",
        foto: "persona6.webp",
        recaudado: 1100,
        objetivo: 2200,
        porcentaje: 50
    },
    {
        id: 7,
        nombre: "Andrea Nicole",
        edad: 23,
        tipoCancer: "Cáncer de Piel",
        ubicacion: "Ahuachapán, Ahuachapán",
        meta: "Estudiar Diseño Gráfico Digital e ilustrar cuentos infantiles sobre superación de adversidades.",
        telefono: "+503 7789-0123",
        foto: "persona7.jpg",
        recaudado: 1800,
        objetivo: 2000,
        porcentaje: 90
    },
    {
        id: 8,
        nombre: "Luis Carlos",
        edad: 25,
        tipoCancer: "Cáncer Testicular",
        ubicacion: "Sonsonate, Sonsonate",
        meta: "Abrir su propio taller o escuela de gastronomía local para rescatar recetas tradicionales.",
        telefono: "+503 7890-1234",
        foto: "persona8.avif",
        recaudado: 1205,
        objetivo: 1800,
        porcentaje: 67
    },
    {
        id: 9,
        nombre: "Mariana Estefanía",
        edad: 20,
        tipoCancer: "Linfoma",
        ubicacion: "Cojutepeque, Cuscatlán",
        meta: "Estudiar Enfermería Profesional para brindar cuidados paliativos con un trato digno y empático.",
        telefono: "+503 7901-2345",
        foto: "persona9.jpg",
        recaudado: 1600,
        objetivo: 3200,
        porcentaje: 50
    },
    {
        id: 10,
        nombre: "José Manuel",
        edad: 22,
        tipoCancer: "Cáncer de Colon",
        ubicacion: "San Vicente, San Vicente",
        meta: "Culminar sus estudios en Agronomía para implementar cultivos sostenibles en su comunidad.",
        telefono: "+503 7012-3456",
        foto: "persona10.jpe",
        recaudado: 2200,
        objetivo: 4000,
        porcentaje: 55
    },
    {
        id: 11,
        nombre: "Elena Beatriz",
        edad: 19,
        tipoCancer: "Leucemia",
        ubicacion: "Usulután, Usulután",
        meta: "Estudiar Psicología para ofrecer terapia de acompañamiento a familias de pacientes oncológicos.",
        telefono: "+503 7111-2222",
        foto: "persona11.avif",
        recaudado: 3400,
        objetivo: 5000,
        porcentaje: 68
    },
    {
        id: 12,
        nombre: "Rodrigo André",
        edad: 21,
        tipoCancer: "Cáncer de Tiroides",
        ubicacion: "Mejicanos, San Salvador",
        meta: "Estudiar Arquitectura de Interiores y diseñar espacios accesibles para personas con movilidad reducida.",
        telefono: "+503 7222-3333",
        foto: "persona12.avif",
        recaudado: 4100,
        objetivo: 6000,
        porcentaje: 68
    },
    {
        id: 13,
        nombre: "Sofía Alejandra",
        edad: 18,
        tipoCancer: "Cáncer de Cuello Uterino",
        ubicacion: "Chalatenango, Chalatenango",
        meta: "Completar su formación en Educación Parvularia para guiar y motivar el desarrollo infantil.",
        telefono: "+503 7333-4444",
        foto: "persona13.avif",
        recaudado: 1500,
        objetivo: 2500,
        porcentaje: 60
    },
    {
        id: 14,
        nombre: "Carlos Eduardo",
        edad: 23,
        tipoCancer: "Cáncer de Pulmón",
        ubicacion: "San Francisco Gotera, Morazán",
        meta: "Estudiar Periodismo de Investigación para amplificar historias sociales de comunidades marginadas.",
        telefono: "+503 7444-5555",
        foto: "persona14.avif",
        recaudado: 2105,
        objetivo: 3500,
        porcentaje: 60
    },
    {
        id: 15,
        nombre: "Daniela Montserrat",
        edad: 20,
        tipoCancer: "Cáncer de Piel",
        ubicacion: "La Unión, La Unión",
        meta: "Estudiar Medicina Veterinaria y fundar un refugio asistencial para animales desprotegidos.",
        telefono: "+503 7555-6666",
        foto: "persona15.jpg",
        recaudado: 1850,
        objetivo: 3000,
        porcentaje: 61
    }
];